/* soapWSDualHttpBinding_USCOREICalculatorDuplexService.h
   Generated by gSOAP 2.8.17r from calculator.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapWSDualHttpBinding_USCOREICalculatorDuplexService_H
#define soapWSDualHttpBinding_USCOREICalculatorDuplexService_H
#include "soapH.h"
class SOAP_CMAC WSDualHttpBinding_USCOREICalculatorDuplexService
{ public:
	struct soap *soap;
	bool own;
	/// Constructor
	WSDualHttpBinding_USCOREICalculatorDuplexService();
	/// Constructor to use/share an engine state
	WSDualHttpBinding_USCOREICalculatorDuplexService(struct soap*);
	/// Constructor with engine input+output mode control
	WSDualHttpBinding_USCOREICalculatorDuplexService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	WSDualHttpBinding_USCOREICalculatorDuplexService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~WSDualHttpBinding_USCOREICalculatorDuplexService();
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void WSDualHttpBinding_USCOREICalculatorDuplexService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	WSDualHttpBinding_USCOREICalculatorDuplexService *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsrm__SequenceType *wsrm__Sequence, int __sizeAckRequested, struct wsrm__AckRequestedType *wsrm__AckRequested, int __sizeSequenceAcknowledgement, struct _wsrm__SequenceAcknowledgement *wsrm__SequenceAcknowledgement, struct wsrm__SequenceFaultType *wsrm__SequenceFault);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service one-way operation 'Clear' (return error code, SOAP_OK (no response), or send_Clear_empty_response())
	virtual	int Clear(_mssadh__Clear *mssadh__Clear) SOAP_PURE_VIRTUAL;
	virtual	int send_Clear_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'AddTo' (return error code, SOAP_OK (no response), or send_AddTo_empty_response())
	virtual	int AddTo(_mssadh__AddTo *mssadh__AddTo) SOAP_PURE_VIRTUAL;
	virtual	int send_AddTo_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'SubtractFrom' (return error code, SOAP_OK (no response), or send_SubtractFrom_empty_response())
	virtual	int SubtractFrom(_mssadh__SubtractFrom *mssadh__SubtractFrom) SOAP_PURE_VIRTUAL;
	virtual	int send_SubtractFrom_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'MultiplyBy' (return error code, SOAP_OK (no response), or send_MultiplyBy_empty_response())
	virtual	int MultiplyBy(_mssadh__MultiplyBy *mssadh__MultiplyBy) SOAP_PURE_VIRTUAL;
	virtual	int send_MultiplyBy_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'DivideBy' (return error code, SOAP_OK (no response), or send_DivideBy_empty_response())
	virtual	int DivideBy(_mssadh__DivideBy *mssadh__DivideBy) SOAP_PURE_VIRTUAL;
	virtual	int send_DivideBy_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'Result' (return error code, SOAP_OK (no response), or send_Result_empty_response())
	virtual	int Result(_mssadh__Result *mssadh__Result) SOAP_PURE_VIRTUAL;
	virtual	int send_Result_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }

	/// Web service one-way operation 'Equation' (return error code, SOAP_OK (no response), or send_Equation_empty_response())
	virtual	int Equation(_mssadh__Equation *mssadh__Equation) SOAP_PURE_VIRTUAL;
	virtual	int send_Equation_empty_response(int httpcode) { return soap_send_empty_response(this->soap, httpcode); }
};
#endif
