/* onvifptzPTZBindingService.cpp
   Generated by gSOAP 2.8.22 from rcx.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "onvifptzPTZBindingService.h"

PTZBindingService::PTZBindingService()
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PTZBindingService::PTZBindingService(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	PTZBindingService_init(_soap->imode, _soap->omode);
}

PTZBindingService::PTZBindingService(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingService_init(iomode, iomode);
}

PTZBindingService::PTZBindingService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingService_init(imode, omode);
}

PTZBindingService::~PTZBindingService()
{	if (this->soap_own)
		soap_free(this->soap);
}

void PTZBindingService::PTZBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ptzws", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void PTZBindingService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void PTZBindingService::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	PTZBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
PTZBindingService *PTZBindingService::copy()
{	PTZBindingService *dup = SOAP_NEW_COPY(PTZBindingService);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

int PTZBindingService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int PTZBindingService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int PTZBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int PTZBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int PTZBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int PTZBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void PTZBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void PTZBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *PTZBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void PTZBindingService::soap_noheader()
{	this->soap->header = NULL;
}

void PTZBindingService::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
}

const SOAP_ENV__Header *PTZBindingService::soap_header()
{	return this->soap->header;
}

int PTZBindingService::run(int port)
{	if (soap_valid_socket(this->soap->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				break;
			soap_destroy(this->soap);
			soap_end(this->soap);
		}
	}
	return this->soap->error;
}

SOAP_SOCKET PTZBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET PTZBindingService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int PTZBindingService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif

int PTZBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->soap->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->soap->max_keep_alive > 0 && !--k)
			this->soap->keep_alive = 0;
#endif

		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if (dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ptzws__GetServiceCapabilities(struct soap*, PTZBindingService*);
static int serve___ptzws__GetConfigurations(struct soap*, PTZBindingService*);
static int serve___ptzws__GetPresets(struct soap*, PTZBindingService*);
static int serve___ptzws__SetPreset(struct soap*, PTZBindingService*);
static int serve___ptzws__RemovePreset(struct soap*, PTZBindingService*);
static int serve___ptzws__GotoPreset(struct soap*, PTZBindingService*);
static int serve___ptzws__GetStatus(struct soap*, PTZBindingService*);
static int serve___ptzws__GetConfiguration(struct soap*, PTZBindingService*);
static int serve___ptzws__GetNodes(struct soap*, PTZBindingService*);
static int serve___ptzws__GetNode(struct soap*, PTZBindingService*);
static int serve___ptzws__SetConfiguration(struct soap*, PTZBindingService*);
static int serve___ptzws__GetConfigurationOptions(struct soap*, PTZBindingService*);
static int serve___ptzws__GotoHomePosition(struct soap*, PTZBindingService*);
static int serve___ptzws__SetHomePosition(struct soap*, PTZBindingService*);
static int serve___ptzws__ContinuousMove(struct soap*, PTZBindingService*);
static int serve___ptzws__RelativeMove(struct soap*, PTZBindingService*);
static int serve___ptzws__SendAuxiliaryCommand(struct soap*, PTZBindingService*);
static int serve___ptzws__AbsoluteMove(struct soap*, PTZBindingService*);
static int serve___ptzws__Stop(struct soap*, PTZBindingService*);
static int serve___ptzws__GetPresetTours(struct soap*, PTZBindingService*);
static int serve___ptzws__GetPresetTour(struct soap*, PTZBindingService*);
static int serve___ptzws__GetPresetTourOptions(struct soap*, PTZBindingService*);
static int serve___ptzws__CreatePresetTour(struct soap*, PTZBindingService*);
static int serve___ptzws__ModifyPresetTour(struct soap*, PTZBindingService*);
static int serve___ptzws__OperatePresetTour(struct soap*, PTZBindingService*);
static int serve___ptzws__RemovePresetTour(struct soap*, PTZBindingService*);
static int serve___ptzws__GetCompatibleConfigurations(struct soap*, PTZBindingService*);

int PTZBindingService::dispatch()
{	return dispatch(this->soap);
}

int PTZBindingService::dispatch(struct soap* soap)
{	PTZBindingService_init(soap->imode, soap->omode);
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetServiceCapabilities"))
		return serve___ptzws__GetServiceCapabilities(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetConfigurations"))
		return serve___ptzws__GetConfigurations(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetPresets"))
		return serve___ptzws__GetPresets(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:SetPreset"))
		return serve___ptzws__SetPreset(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:RemovePreset"))
		return serve___ptzws__RemovePreset(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GotoPreset"))
		return serve___ptzws__GotoPreset(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetStatus"))
		return serve___ptzws__GetStatus(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetConfiguration"))
		return serve___ptzws__GetConfiguration(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetNodes"))
		return serve___ptzws__GetNodes(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetNode"))
		return serve___ptzws__GetNode(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:SetConfiguration"))
		return serve___ptzws__SetConfiguration(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetConfigurationOptions"))
		return serve___ptzws__GetConfigurationOptions(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GotoHomePosition"))
		return serve___ptzws__GotoHomePosition(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:SetHomePosition"))
		return serve___ptzws__SetHomePosition(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:ContinuousMove"))
		return serve___ptzws__ContinuousMove(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:RelativeMove"))
		return serve___ptzws__RelativeMove(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:SendAuxiliaryCommand"))
		return serve___ptzws__SendAuxiliaryCommand(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:AbsoluteMove"))
		return serve___ptzws__AbsoluteMove(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:Stop"))
		return serve___ptzws__Stop(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetPresetTours"))
		return serve___ptzws__GetPresetTours(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetPresetTour"))
		return serve___ptzws__GetPresetTour(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetPresetTourOptions"))
		return serve___ptzws__GetPresetTourOptions(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:CreatePresetTour"))
		return serve___ptzws__CreatePresetTour(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:ModifyPresetTour"))
		return serve___ptzws__ModifyPresetTour(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:OperatePresetTour"))
		return serve___ptzws__OperatePresetTour(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:RemovePresetTour"))
		return serve___ptzws__RemovePresetTour(soap, this);
	if (!soap_match_tag(soap, soap->tag, "ptzws:GetCompatibleConfigurations"))
		return serve___ptzws__GetCompatibleConfigurations(soap, this);
	return soap->error = SOAP_NO_METHOD;
}

static int serve___ptzws__GetServiceCapabilities(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetServiceCapabilities soap_tmp___ptzws__GetServiceCapabilities;
	_ptzws__GetServiceCapabilitiesResponse ptzws__GetServiceCapabilitiesResponse;
	ptzws__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___ptzws__GetServiceCapabilities(soap, &soap_tmp___ptzws__GetServiceCapabilities);
	if (!soap_get___ptzws__GetServiceCapabilities(soap, &soap_tmp___ptzws__GetServiceCapabilities, "-ptzws:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetServiceCapabilities(soap_tmp___ptzws__GetServiceCapabilities.ptzws__GetServiceCapabilities, ptzws__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetServiceCapabilitiesResponse.soap_put(soap, "ptzws:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetServiceCapabilitiesResponse.soap_put(soap, "ptzws:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetConfigurations(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetConfigurations soap_tmp___ptzws__GetConfigurations;
	_ptzws__GetConfigurationsResponse ptzws__GetConfigurationsResponse;
	ptzws__GetConfigurationsResponse.soap_default(soap);
	soap_default___ptzws__GetConfigurations(soap, &soap_tmp___ptzws__GetConfigurations);
	if (!soap_get___ptzws__GetConfigurations(soap, &soap_tmp___ptzws__GetConfigurations, "-ptzws:GetConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetConfigurations(soap_tmp___ptzws__GetConfigurations.ptzws__GetConfigurations, ptzws__GetConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetConfigurationsResponse.soap_put(soap, "ptzws:GetConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetConfigurationsResponse.soap_put(soap, "ptzws:GetConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetPresets(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetPresets soap_tmp___ptzws__GetPresets;
	_ptzws__GetPresetsResponse ptzws__GetPresetsResponse;
	ptzws__GetPresetsResponse.soap_default(soap);
	soap_default___ptzws__GetPresets(soap, &soap_tmp___ptzws__GetPresets);
	if (!soap_get___ptzws__GetPresets(soap, &soap_tmp___ptzws__GetPresets, "-ptzws:GetPresets", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetPresets(soap_tmp___ptzws__GetPresets.ptzws__GetPresets, ptzws__GetPresetsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetPresetsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetPresetsResponse.soap_put(soap, "ptzws:GetPresetsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetPresetsResponse.soap_put(soap, "ptzws:GetPresetsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__SetPreset(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__SetPreset soap_tmp___ptzws__SetPreset;
	_ptzws__SetPresetResponse ptzws__SetPresetResponse;
	ptzws__SetPresetResponse.soap_default(soap);
	soap_default___ptzws__SetPreset(soap, &soap_tmp___ptzws__SetPreset);
	if (!soap_get___ptzws__SetPreset(soap, &soap_tmp___ptzws__SetPreset, "-ptzws:SetPreset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetPreset(soap_tmp___ptzws__SetPreset.ptzws__SetPreset, ptzws__SetPresetResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__SetPresetResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__SetPresetResponse.soap_put(soap, "ptzws:SetPresetResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__SetPresetResponse.soap_put(soap, "ptzws:SetPresetResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__RemovePreset(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__RemovePreset soap_tmp___ptzws__RemovePreset;
	_ptzws__RemovePresetResponse ptzws__RemovePresetResponse;
	ptzws__RemovePresetResponse.soap_default(soap);
	soap_default___ptzws__RemovePreset(soap, &soap_tmp___ptzws__RemovePreset);
	if (!soap_get___ptzws__RemovePreset(soap, &soap_tmp___ptzws__RemovePreset, "-ptzws:RemovePreset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->RemovePreset(soap_tmp___ptzws__RemovePreset.ptzws__RemovePreset, ptzws__RemovePresetResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__RemovePresetResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__RemovePresetResponse.soap_put(soap, "ptzws:RemovePresetResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__RemovePresetResponse.soap_put(soap, "ptzws:RemovePresetResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GotoPreset(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GotoPreset soap_tmp___ptzws__GotoPreset;
	_ptzws__GotoPresetResponse ptzws__GotoPresetResponse;
	ptzws__GotoPresetResponse.soap_default(soap);
	soap_default___ptzws__GotoPreset(soap, &soap_tmp___ptzws__GotoPreset);
	if (!soap_get___ptzws__GotoPreset(soap, &soap_tmp___ptzws__GotoPreset, "-ptzws:GotoPreset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GotoPreset(soap_tmp___ptzws__GotoPreset.ptzws__GotoPreset, ptzws__GotoPresetResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GotoPresetResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GotoPresetResponse.soap_put(soap, "ptzws:GotoPresetResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GotoPresetResponse.soap_put(soap, "ptzws:GotoPresetResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetStatus(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetStatus soap_tmp___ptzws__GetStatus;
	_ptzws__GetStatusResponse ptzws__GetStatusResponse;
	ptzws__GetStatusResponse.soap_default(soap);
	soap_default___ptzws__GetStatus(soap, &soap_tmp___ptzws__GetStatus);
	if (!soap_get___ptzws__GetStatus(soap, &soap_tmp___ptzws__GetStatus, "-ptzws:GetStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetStatus(soap_tmp___ptzws__GetStatus.ptzws__GetStatus, ptzws__GetStatusResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetStatusResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetStatusResponse.soap_put(soap, "ptzws:GetStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetStatusResponse.soap_put(soap, "ptzws:GetStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetConfiguration(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetConfiguration soap_tmp___ptzws__GetConfiguration;
	_ptzws__GetConfigurationResponse ptzws__GetConfigurationResponse;
	ptzws__GetConfigurationResponse.soap_default(soap);
	soap_default___ptzws__GetConfiguration(soap, &soap_tmp___ptzws__GetConfiguration);
	if (!soap_get___ptzws__GetConfiguration(soap, &soap_tmp___ptzws__GetConfiguration, "-ptzws:GetConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetConfiguration(soap_tmp___ptzws__GetConfiguration.ptzws__GetConfiguration, ptzws__GetConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetConfigurationResponse.soap_put(soap, "ptzws:GetConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetConfigurationResponse.soap_put(soap, "ptzws:GetConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetNodes(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetNodes soap_tmp___ptzws__GetNodes;
	_ptzws__GetNodesResponse ptzws__GetNodesResponse;
	ptzws__GetNodesResponse.soap_default(soap);
	soap_default___ptzws__GetNodes(soap, &soap_tmp___ptzws__GetNodes);
	if (!soap_get___ptzws__GetNodes(soap, &soap_tmp___ptzws__GetNodes, "-ptzws:GetNodes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetNodes(soap_tmp___ptzws__GetNodes.ptzws__GetNodes, ptzws__GetNodesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetNodesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetNodesResponse.soap_put(soap, "ptzws:GetNodesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetNodesResponse.soap_put(soap, "ptzws:GetNodesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetNode(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetNode soap_tmp___ptzws__GetNode;
	_ptzws__GetNodeResponse ptzws__GetNodeResponse;
	ptzws__GetNodeResponse.soap_default(soap);
	soap_default___ptzws__GetNode(soap, &soap_tmp___ptzws__GetNode);
	if (!soap_get___ptzws__GetNode(soap, &soap_tmp___ptzws__GetNode, "-ptzws:GetNode", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetNode(soap_tmp___ptzws__GetNode.ptzws__GetNode, ptzws__GetNodeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetNodeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetNodeResponse.soap_put(soap, "ptzws:GetNodeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetNodeResponse.soap_put(soap, "ptzws:GetNodeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__SetConfiguration(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__SetConfiguration soap_tmp___ptzws__SetConfiguration;
	_ptzws__SetConfigurationResponse ptzws__SetConfigurationResponse;
	ptzws__SetConfigurationResponse.soap_default(soap);
	soap_default___ptzws__SetConfiguration(soap, &soap_tmp___ptzws__SetConfiguration);
	if (!soap_get___ptzws__SetConfiguration(soap, &soap_tmp___ptzws__SetConfiguration, "-ptzws:SetConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetConfiguration(soap_tmp___ptzws__SetConfiguration.ptzws__SetConfiguration, ptzws__SetConfigurationResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__SetConfigurationResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__SetConfigurationResponse.soap_put(soap, "ptzws:SetConfigurationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__SetConfigurationResponse.soap_put(soap, "ptzws:SetConfigurationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetConfigurationOptions(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetConfigurationOptions soap_tmp___ptzws__GetConfigurationOptions;
	_ptzws__GetConfigurationOptionsResponse ptzws__GetConfigurationOptionsResponse;
	ptzws__GetConfigurationOptionsResponse.soap_default(soap);
	soap_default___ptzws__GetConfigurationOptions(soap, &soap_tmp___ptzws__GetConfigurationOptions);
	if (!soap_get___ptzws__GetConfigurationOptions(soap, &soap_tmp___ptzws__GetConfigurationOptions, "-ptzws:GetConfigurationOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetConfigurationOptions(soap_tmp___ptzws__GetConfigurationOptions.ptzws__GetConfigurationOptions, ptzws__GetConfigurationOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetConfigurationOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetConfigurationOptionsResponse.soap_put(soap, "ptzws:GetConfigurationOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetConfigurationOptionsResponse.soap_put(soap, "ptzws:GetConfigurationOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GotoHomePosition(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GotoHomePosition soap_tmp___ptzws__GotoHomePosition;
	_ptzws__GotoHomePositionResponse ptzws__GotoHomePositionResponse;
	ptzws__GotoHomePositionResponse.soap_default(soap);
	soap_default___ptzws__GotoHomePosition(soap, &soap_tmp___ptzws__GotoHomePosition);
	if (!soap_get___ptzws__GotoHomePosition(soap, &soap_tmp___ptzws__GotoHomePosition, "-ptzws:GotoHomePosition", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GotoHomePosition(soap_tmp___ptzws__GotoHomePosition.ptzws__GotoHomePosition, ptzws__GotoHomePositionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GotoHomePositionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GotoHomePositionResponse.soap_put(soap, "ptzws:GotoHomePositionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GotoHomePositionResponse.soap_put(soap, "ptzws:GotoHomePositionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__SetHomePosition(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__SetHomePosition soap_tmp___ptzws__SetHomePosition;
	_ptzws__SetHomePositionResponse ptzws__SetHomePositionResponse;
	ptzws__SetHomePositionResponse.soap_default(soap);
	soap_default___ptzws__SetHomePosition(soap, &soap_tmp___ptzws__SetHomePosition);
	if (!soap_get___ptzws__SetHomePosition(soap, &soap_tmp___ptzws__SetHomePosition, "-ptzws:SetHomePosition", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SetHomePosition(soap_tmp___ptzws__SetHomePosition.ptzws__SetHomePosition, ptzws__SetHomePositionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__SetHomePositionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__SetHomePositionResponse.soap_put(soap, "ptzws:SetHomePositionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__SetHomePositionResponse.soap_put(soap, "ptzws:SetHomePositionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__ContinuousMove(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__ContinuousMove soap_tmp___ptzws__ContinuousMove;
	_ptzws__ContinuousMoveResponse ptzws__ContinuousMoveResponse;
	ptzws__ContinuousMoveResponse.soap_default(soap);
	soap_default___ptzws__ContinuousMove(soap, &soap_tmp___ptzws__ContinuousMove);
	if (!soap_get___ptzws__ContinuousMove(soap, &soap_tmp___ptzws__ContinuousMove, "-ptzws:ContinuousMove", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->ContinuousMove(soap_tmp___ptzws__ContinuousMove.ptzws__ContinuousMove, ptzws__ContinuousMoveResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__ContinuousMoveResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__ContinuousMoveResponse.soap_put(soap, "ptzws:ContinuousMoveResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__ContinuousMoveResponse.soap_put(soap, "ptzws:ContinuousMoveResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__RelativeMove(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__RelativeMove soap_tmp___ptzws__RelativeMove;
	_ptzws__RelativeMoveResponse ptzws__RelativeMoveResponse;
	ptzws__RelativeMoveResponse.soap_default(soap);
	soap_default___ptzws__RelativeMove(soap, &soap_tmp___ptzws__RelativeMove);
	if (!soap_get___ptzws__RelativeMove(soap, &soap_tmp___ptzws__RelativeMove, "-ptzws:RelativeMove", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->RelativeMove(soap_tmp___ptzws__RelativeMove.ptzws__RelativeMove, ptzws__RelativeMoveResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__RelativeMoveResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__RelativeMoveResponse.soap_put(soap, "ptzws:RelativeMoveResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__RelativeMoveResponse.soap_put(soap, "ptzws:RelativeMoveResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__SendAuxiliaryCommand(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__SendAuxiliaryCommand soap_tmp___ptzws__SendAuxiliaryCommand;
	_ptzws__SendAuxiliaryCommandResponse ptzws__SendAuxiliaryCommandResponse;
	ptzws__SendAuxiliaryCommandResponse.soap_default(soap);
	soap_default___ptzws__SendAuxiliaryCommand(soap, &soap_tmp___ptzws__SendAuxiliaryCommand);
	if (!soap_get___ptzws__SendAuxiliaryCommand(soap, &soap_tmp___ptzws__SendAuxiliaryCommand, "-ptzws:SendAuxiliaryCommand", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->SendAuxiliaryCommand(soap_tmp___ptzws__SendAuxiliaryCommand.ptzws__SendAuxiliaryCommand, ptzws__SendAuxiliaryCommandResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__SendAuxiliaryCommandResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__SendAuxiliaryCommandResponse.soap_put(soap, "ptzws:SendAuxiliaryCommandResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__SendAuxiliaryCommandResponse.soap_put(soap, "ptzws:SendAuxiliaryCommandResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__AbsoluteMove(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__AbsoluteMove soap_tmp___ptzws__AbsoluteMove;
	_ptzws__AbsoluteMoveResponse ptzws__AbsoluteMoveResponse;
	ptzws__AbsoluteMoveResponse.soap_default(soap);
	soap_default___ptzws__AbsoluteMove(soap, &soap_tmp___ptzws__AbsoluteMove);
	if (!soap_get___ptzws__AbsoluteMove(soap, &soap_tmp___ptzws__AbsoluteMove, "-ptzws:AbsoluteMove", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->AbsoluteMove(soap_tmp___ptzws__AbsoluteMove.ptzws__AbsoluteMove, ptzws__AbsoluteMoveResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__AbsoluteMoveResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__AbsoluteMoveResponse.soap_put(soap, "ptzws:AbsoluteMoveResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__AbsoluteMoveResponse.soap_put(soap, "ptzws:AbsoluteMoveResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__Stop(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__Stop soap_tmp___ptzws__Stop;
	_ptzws__StopResponse ptzws__StopResponse;
	ptzws__StopResponse.soap_default(soap);
	soap_default___ptzws__Stop(soap, &soap_tmp___ptzws__Stop);
	if (!soap_get___ptzws__Stop(soap, &soap_tmp___ptzws__Stop, "-ptzws:Stop", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->Stop(soap_tmp___ptzws__Stop.ptzws__Stop, ptzws__StopResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__StopResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__StopResponse.soap_put(soap, "ptzws:StopResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__StopResponse.soap_put(soap, "ptzws:StopResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetPresetTours(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetPresetTours soap_tmp___ptzws__GetPresetTours;
	_ptzws__GetPresetToursResponse ptzws__GetPresetToursResponse;
	ptzws__GetPresetToursResponse.soap_default(soap);
	soap_default___ptzws__GetPresetTours(soap, &soap_tmp___ptzws__GetPresetTours);
	if (!soap_get___ptzws__GetPresetTours(soap, &soap_tmp___ptzws__GetPresetTours, "-ptzws:GetPresetTours", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetPresetTours(soap_tmp___ptzws__GetPresetTours.ptzws__GetPresetTours, ptzws__GetPresetToursResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetPresetToursResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetPresetToursResponse.soap_put(soap, "ptzws:GetPresetToursResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetPresetToursResponse.soap_put(soap, "ptzws:GetPresetToursResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetPresetTour(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetPresetTour soap_tmp___ptzws__GetPresetTour;
	_ptzws__GetPresetTourResponse ptzws__GetPresetTourResponse;
	ptzws__GetPresetTourResponse.soap_default(soap);
	soap_default___ptzws__GetPresetTour(soap, &soap_tmp___ptzws__GetPresetTour);
	if (!soap_get___ptzws__GetPresetTour(soap, &soap_tmp___ptzws__GetPresetTour, "-ptzws:GetPresetTour", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetPresetTour(soap_tmp___ptzws__GetPresetTour.ptzws__GetPresetTour, ptzws__GetPresetTourResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetPresetTourResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetPresetTourResponse.soap_put(soap, "ptzws:GetPresetTourResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetPresetTourResponse.soap_put(soap, "ptzws:GetPresetTourResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetPresetTourOptions(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetPresetTourOptions soap_tmp___ptzws__GetPresetTourOptions;
	_ptzws__GetPresetTourOptionsResponse ptzws__GetPresetTourOptionsResponse;
	ptzws__GetPresetTourOptionsResponse.soap_default(soap);
	soap_default___ptzws__GetPresetTourOptions(soap, &soap_tmp___ptzws__GetPresetTourOptions);
	if (!soap_get___ptzws__GetPresetTourOptions(soap, &soap_tmp___ptzws__GetPresetTourOptions, "-ptzws:GetPresetTourOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetPresetTourOptions(soap_tmp___ptzws__GetPresetTourOptions.ptzws__GetPresetTourOptions, ptzws__GetPresetTourOptionsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetPresetTourOptionsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetPresetTourOptionsResponse.soap_put(soap, "ptzws:GetPresetTourOptionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetPresetTourOptionsResponse.soap_put(soap, "ptzws:GetPresetTourOptionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__CreatePresetTour(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__CreatePresetTour soap_tmp___ptzws__CreatePresetTour;
	_ptzws__CreatePresetTourResponse ptzws__CreatePresetTourResponse;
	ptzws__CreatePresetTourResponse.soap_default(soap);
	soap_default___ptzws__CreatePresetTour(soap, &soap_tmp___ptzws__CreatePresetTour);
	if (!soap_get___ptzws__CreatePresetTour(soap, &soap_tmp___ptzws__CreatePresetTour, "-ptzws:CreatePresetTour", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreatePresetTour(soap_tmp___ptzws__CreatePresetTour.ptzws__CreatePresetTour, ptzws__CreatePresetTourResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__CreatePresetTourResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__CreatePresetTourResponse.soap_put(soap, "ptzws:CreatePresetTourResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__CreatePresetTourResponse.soap_put(soap, "ptzws:CreatePresetTourResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__ModifyPresetTour(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__ModifyPresetTour soap_tmp___ptzws__ModifyPresetTour;
	_ptzws__ModifyPresetTourResponse ptzws__ModifyPresetTourResponse;
	ptzws__ModifyPresetTourResponse.soap_default(soap);
	soap_default___ptzws__ModifyPresetTour(soap, &soap_tmp___ptzws__ModifyPresetTour);
	if (!soap_get___ptzws__ModifyPresetTour(soap, &soap_tmp___ptzws__ModifyPresetTour, "-ptzws:ModifyPresetTour", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->ModifyPresetTour(soap_tmp___ptzws__ModifyPresetTour.ptzws__ModifyPresetTour, ptzws__ModifyPresetTourResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__ModifyPresetTourResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__ModifyPresetTourResponse.soap_put(soap, "ptzws:ModifyPresetTourResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__ModifyPresetTourResponse.soap_put(soap, "ptzws:ModifyPresetTourResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__OperatePresetTour(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__OperatePresetTour soap_tmp___ptzws__OperatePresetTour;
	_ptzws__OperatePresetTourResponse ptzws__OperatePresetTourResponse;
	ptzws__OperatePresetTourResponse.soap_default(soap);
	soap_default___ptzws__OperatePresetTour(soap, &soap_tmp___ptzws__OperatePresetTour);
	if (!soap_get___ptzws__OperatePresetTour(soap, &soap_tmp___ptzws__OperatePresetTour, "-ptzws:OperatePresetTour", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->OperatePresetTour(soap_tmp___ptzws__OperatePresetTour.ptzws__OperatePresetTour, ptzws__OperatePresetTourResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__OperatePresetTourResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__OperatePresetTourResponse.soap_put(soap, "ptzws:OperatePresetTourResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__OperatePresetTourResponse.soap_put(soap, "ptzws:OperatePresetTourResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__RemovePresetTour(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__RemovePresetTour soap_tmp___ptzws__RemovePresetTour;
	_ptzws__RemovePresetTourResponse ptzws__RemovePresetTourResponse;
	ptzws__RemovePresetTourResponse.soap_default(soap);
	soap_default___ptzws__RemovePresetTour(soap, &soap_tmp___ptzws__RemovePresetTour);
	if (!soap_get___ptzws__RemovePresetTour(soap, &soap_tmp___ptzws__RemovePresetTour, "-ptzws:RemovePresetTour", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->RemovePresetTour(soap_tmp___ptzws__RemovePresetTour.ptzws__RemovePresetTour, ptzws__RemovePresetTourResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__RemovePresetTourResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__RemovePresetTourResponse.soap_put(soap, "ptzws:RemovePresetTourResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__RemovePresetTourResponse.soap_put(soap, "ptzws:RemovePresetTourResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ptzws__GetCompatibleConfigurations(struct soap *soap, PTZBindingService *service)
{	struct __ptzws__GetCompatibleConfigurations soap_tmp___ptzws__GetCompatibleConfigurations;
	_ptzws__GetCompatibleConfigurationsResponse ptzws__GetCompatibleConfigurationsResponse;
	ptzws__GetCompatibleConfigurationsResponse.soap_default(soap);
	soap_default___ptzws__GetCompatibleConfigurations(soap, &soap_tmp___ptzws__GetCompatibleConfigurations);
	if (!soap_get___ptzws__GetCompatibleConfigurations(soap, &soap_tmp___ptzws__GetCompatibleConfigurations, "-ptzws:GetCompatibleConfigurations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetCompatibleConfigurations(soap_tmp___ptzws__GetCompatibleConfigurations.ptzws__GetCompatibleConfigurations, ptzws__GetCompatibleConfigurationsResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	ptzws__GetCompatibleConfigurationsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ptzws__GetCompatibleConfigurationsResponse.soap_put(soap, "ptzws:GetCompatibleConfigurationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ptzws__GetCompatibleConfigurationsResponse.soap_put(soap, "ptzws:GetCompatibleConfigurationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
