/* onvifptzPTZBindingProxy.cpp
   Generated by gSOAP 2.8.22 from rcx.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "onvifptzPTZBindingProxy.h"

PTZBindingProxy::PTZBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PTZBindingProxy::PTZBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	PTZBindingProxy_init(_soap->imode, _soap->omode);
}

PTZBindingProxy::PTZBindingProxy(const char *url)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

PTZBindingProxy::PTZBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingProxy_init(iomode, iomode);
}

PTZBindingProxy::PTZBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

PTZBindingProxy::PTZBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	PTZBindingProxy_init(imode, omode);
}

PTZBindingProxy::~PTZBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void PTZBindingProxy::PTZBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
	{"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
	{"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
	{"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
	{"ptzws", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void PTZBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void PTZBindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	PTZBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void PTZBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void PTZBindingProxy::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
}

const SOAP_ENV__Header *PTZBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *PTZBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *PTZBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *PTZBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int PTZBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int PTZBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void PTZBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void PTZBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *PTZBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int PTZBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ptzws__GetServiceCapabilities *ptzws__GetServiceCapabilities, _ptzws__GetServiceCapabilitiesResponse &ptzws__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetServiceCapabilities soap_tmp___ptzws__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetServiceCapabilities.ptzws__GetServiceCapabilities = ptzws__GetServiceCapabilities;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetServiceCapabilities(soap, &soap_tmp___ptzws__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetServiceCapabilities(soap, &soap_tmp___ptzws__GetServiceCapabilities, "-ptzws:GetServiceCapabilities", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetServiceCapabilities(soap, &soap_tmp___ptzws__GetServiceCapabilities, "-ptzws:GetServiceCapabilities", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetServiceCapabilitiesResponse)
		return soap_closesock(soap);
	ptzws__GetServiceCapabilitiesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetServiceCapabilitiesResponse.soap_get(soap, "ptzws:GetServiceCapabilitiesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfigurations(const char *endpoint, const char *soap_action, _ptzws__GetConfigurations *ptzws__GetConfigurations, _ptzws__GetConfigurationsResponse &ptzws__GetConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetConfigurations soap_tmp___ptzws__GetConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetConfigurations.ptzws__GetConfigurations = ptzws__GetConfigurations;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetConfigurations(soap, &soap_tmp___ptzws__GetConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetConfigurations(soap, &soap_tmp___ptzws__GetConfigurations, "-ptzws:GetConfigurations", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetConfigurations(soap, &soap_tmp___ptzws__GetConfigurations, "-ptzws:GetConfigurations", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetConfigurationsResponse)
		return soap_closesock(soap);
	ptzws__GetConfigurationsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetConfigurationsResponse.soap_get(soap, "ptzws:GetConfigurationsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresets(const char *endpoint, const char *soap_action, _ptzws__GetPresets *ptzws__GetPresets, _ptzws__GetPresetsResponse &ptzws__GetPresetsResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetPresets soap_tmp___ptzws__GetPresets;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresets";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetPresets.ptzws__GetPresets = ptzws__GetPresets;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetPresets(soap, &soap_tmp___ptzws__GetPresets);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetPresets(soap, &soap_tmp___ptzws__GetPresets, "-ptzws:GetPresets", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetPresets(soap, &soap_tmp___ptzws__GetPresets, "-ptzws:GetPresets", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetPresetsResponse)
		return soap_closesock(soap);
	ptzws__GetPresetsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetPresetsResponse.soap_get(soap, "ptzws:GetPresetsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetPreset(const char *endpoint, const char *soap_action, _ptzws__SetPreset *ptzws__SetPreset, _ptzws__SetPresetResponse &ptzws__SetPresetResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__SetPreset soap_tmp___ptzws__SetPreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetPreset";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__SetPreset.ptzws__SetPreset = ptzws__SetPreset;
	soap_serializeheader(soap);
	soap_serialize___ptzws__SetPreset(soap, &soap_tmp___ptzws__SetPreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__SetPreset(soap, &soap_tmp___ptzws__SetPreset, "-ptzws:SetPreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__SetPreset(soap, &soap_tmp___ptzws__SetPreset, "-ptzws:SetPreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__SetPresetResponse)
		return soap_closesock(soap);
	ptzws__SetPresetResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__SetPresetResponse.soap_get(soap, "ptzws:SetPresetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RemovePreset(const char *endpoint, const char *soap_action, _ptzws__RemovePreset *ptzws__RemovePreset, _ptzws__RemovePresetResponse &ptzws__RemovePresetResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__RemovePreset soap_tmp___ptzws__RemovePreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__RemovePreset.ptzws__RemovePreset = ptzws__RemovePreset;
	soap_serializeheader(soap);
	soap_serialize___ptzws__RemovePreset(soap, &soap_tmp___ptzws__RemovePreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__RemovePreset(soap, &soap_tmp___ptzws__RemovePreset, "-ptzws:RemovePreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__RemovePreset(soap, &soap_tmp___ptzws__RemovePreset, "-ptzws:RemovePreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__RemovePresetResponse)
		return soap_closesock(soap);
	ptzws__RemovePresetResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__RemovePresetResponse.soap_get(soap, "ptzws:RemovePresetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GotoPreset(const char *endpoint, const char *soap_action, _ptzws__GotoPreset *ptzws__GotoPreset, _ptzws__GotoPresetResponse &ptzws__GotoPresetResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GotoPreset soap_tmp___ptzws__GotoPreset;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GotoPreset.ptzws__GotoPreset = ptzws__GotoPreset;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GotoPreset(soap, &soap_tmp___ptzws__GotoPreset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GotoPreset(soap, &soap_tmp___ptzws__GotoPreset, "-ptzws:GotoPreset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GotoPreset(soap, &soap_tmp___ptzws__GotoPreset, "-ptzws:GotoPreset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GotoPresetResponse)
		return soap_closesock(soap);
	ptzws__GotoPresetResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GotoPresetResponse.soap_get(soap, "ptzws:GotoPresetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetStatus(const char *endpoint, const char *soap_action, _ptzws__GetStatus *ptzws__GetStatus, _ptzws__GetStatusResponse &ptzws__GetStatusResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetStatus soap_tmp___ptzws__GetStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetStatus";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetStatus.ptzws__GetStatus = ptzws__GetStatus;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetStatus(soap, &soap_tmp___ptzws__GetStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetStatus(soap, &soap_tmp___ptzws__GetStatus, "-ptzws:GetStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetStatus(soap, &soap_tmp___ptzws__GetStatus, "-ptzws:GetStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetStatusResponse)
		return soap_closesock(soap);
	ptzws__GetStatusResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetStatusResponse.soap_get(soap, "ptzws:GetStatusResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfiguration(const char *endpoint, const char *soap_action, _ptzws__GetConfiguration *ptzws__GetConfiguration, _ptzws__GetConfigurationResponse &ptzws__GetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetConfiguration soap_tmp___ptzws__GetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetConfiguration.ptzws__GetConfiguration = ptzws__GetConfiguration;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetConfiguration(soap, &soap_tmp___ptzws__GetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetConfiguration(soap, &soap_tmp___ptzws__GetConfiguration, "-ptzws:GetConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetConfiguration(soap, &soap_tmp___ptzws__GetConfiguration, "-ptzws:GetConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetConfigurationResponse)
		return soap_closesock(soap);
	ptzws__GetConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetConfigurationResponse.soap_get(soap, "ptzws:GetConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetNodes(const char *endpoint, const char *soap_action, _ptzws__GetNodes *ptzws__GetNodes, _ptzws__GetNodesResponse &ptzws__GetNodesResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetNodes soap_tmp___ptzws__GetNodes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetNodes";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetNodes.ptzws__GetNodes = ptzws__GetNodes;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetNodes(soap, &soap_tmp___ptzws__GetNodes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetNodes(soap, &soap_tmp___ptzws__GetNodes, "-ptzws:GetNodes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetNodes(soap, &soap_tmp___ptzws__GetNodes, "-ptzws:GetNodes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetNodesResponse)
		return soap_closesock(soap);
	ptzws__GetNodesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetNodesResponse.soap_get(soap, "ptzws:GetNodesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetNode(const char *endpoint, const char *soap_action, _ptzws__GetNode *ptzws__GetNode, _ptzws__GetNodeResponse &ptzws__GetNodeResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetNode soap_tmp___ptzws__GetNode;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetNode";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetNode.ptzws__GetNode = ptzws__GetNode;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetNode(soap, &soap_tmp___ptzws__GetNode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetNode(soap, &soap_tmp___ptzws__GetNode, "-ptzws:GetNode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetNode(soap, &soap_tmp___ptzws__GetNode, "-ptzws:GetNode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetNodeResponse)
		return soap_closesock(soap);
	ptzws__GetNodeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetNodeResponse.soap_get(soap, "ptzws:GetNodeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetConfiguration(const char *endpoint, const char *soap_action, _ptzws__SetConfiguration *ptzws__SetConfiguration, _ptzws__SetConfigurationResponse &ptzws__SetConfigurationResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__SetConfiguration soap_tmp___ptzws__SetConfiguration;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__SetConfiguration.ptzws__SetConfiguration = ptzws__SetConfiguration;
	soap_serializeheader(soap);
	soap_serialize___ptzws__SetConfiguration(soap, &soap_tmp___ptzws__SetConfiguration);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__SetConfiguration(soap, &soap_tmp___ptzws__SetConfiguration, "-ptzws:SetConfiguration", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__SetConfiguration(soap, &soap_tmp___ptzws__SetConfiguration, "-ptzws:SetConfiguration", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__SetConfigurationResponse)
		return soap_closesock(soap);
	ptzws__SetConfigurationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__SetConfigurationResponse.soap_get(soap, "ptzws:SetConfigurationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetConfigurationOptions(const char *endpoint, const char *soap_action, _ptzws__GetConfigurationOptions *ptzws__GetConfigurationOptions, _ptzws__GetConfigurationOptionsResponse &ptzws__GetConfigurationOptionsResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetConfigurationOptions soap_tmp___ptzws__GetConfigurationOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetConfigurationOptions.ptzws__GetConfigurationOptions = ptzws__GetConfigurationOptions;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetConfigurationOptions(soap, &soap_tmp___ptzws__GetConfigurationOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetConfigurationOptions(soap, &soap_tmp___ptzws__GetConfigurationOptions, "-ptzws:GetConfigurationOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetConfigurationOptions(soap, &soap_tmp___ptzws__GetConfigurationOptions, "-ptzws:GetConfigurationOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetConfigurationOptionsResponse)
		return soap_closesock(soap);
	ptzws__GetConfigurationOptionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetConfigurationOptionsResponse.soap_get(soap, "ptzws:GetConfigurationOptionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GotoHomePosition(const char *endpoint, const char *soap_action, _ptzws__GotoHomePosition *ptzws__GotoHomePosition, _ptzws__GotoHomePositionResponse &ptzws__GotoHomePositionResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GotoHomePosition soap_tmp___ptzws__GotoHomePosition;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GotoHomePosition.ptzws__GotoHomePosition = ptzws__GotoHomePosition;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GotoHomePosition(soap, &soap_tmp___ptzws__GotoHomePosition);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GotoHomePosition(soap, &soap_tmp___ptzws__GotoHomePosition, "-ptzws:GotoHomePosition", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GotoHomePosition(soap, &soap_tmp___ptzws__GotoHomePosition, "-ptzws:GotoHomePosition", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GotoHomePositionResponse)
		return soap_closesock(soap);
	ptzws__GotoHomePositionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GotoHomePositionResponse.soap_get(soap, "ptzws:GotoHomePositionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SetHomePosition(const char *endpoint, const char *soap_action, _ptzws__SetHomePosition *ptzws__SetHomePosition, _ptzws__SetHomePositionResponse &ptzws__SetHomePositionResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__SetHomePosition soap_tmp___ptzws__SetHomePosition;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__SetHomePosition.ptzws__SetHomePosition = ptzws__SetHomePosition;
	soap_serializeheader(soap);
	soap_serialize___ptzws__SetHomePosition(soap, &soap_tmp___ptzws__SetHomePosition);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__SetHomePosition(soap, &soap_tmp___ptzws__SetHomePosition, "-ptzws:SetHomePosition", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__SetHomePosition(soap, &soap_tmp___ptzws__SetHomePosition, "-ptzws:SetHomePosition", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__SetHomePositionResponse)
		return soap_closesock(soap);
	ptzws__SetHomePositionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__SetHomePositionResponse.soap_get(soap, "ptzws:SetHomePositionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::ContinuousMove(const char *endpoint, const char *soap_action, _ptzws__ContinuousMove *ptzws__ContinuousMove, _ptzws__ContinuousMoveResponse &ptzws__ContinuousMoveResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__ContinuousMove soap_tmp___ptzws__ContinuousMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__ContinuousMove.ptzws__ContinuousMove = ptzws__ContinuousMove;
	soap_serializeheader(soap);
	soap_serialize___ptzws__ContinuousMove(soap, &soap_tmp___ptzws__ContinuousMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__ContinuousMove(soap, &soap_tmp___ptzws__ContinuousMove, "-ptzws:ContinuousMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__ContinuousMove(soap, &soap_tmp___ptzws__ContinuousMove, "-ptzws:ContinuousMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__ContinuousMoveResponse)
		return soap_closesock(soap);
	ptzws__ContinuousMoveResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__ContinuousMoveResponse.soap_get(soap, "ptzws:ContinuousMoveResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RelativeMove(const char *endpoint, const char *soap_action, _ptzws__RelativeMove *ptzws__RelativeMove, _ptzws__RelativeMoveResponse &ptzws__RelativeMoveResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__RelativeMove soap_tmp___ptzws__RelativeMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__RelativeMove.ptzws__RelativeMove = ptzws__RelativeMove;
	soap_serializeheader(soap);
	soap_serialize___ptzws__RelativeMove(soap, &soap_tmp___ptzws__RelativeMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__RelativeMove(soap, &soap_tmp___ptzws__RelativeMove, "-ptzws:RelativeMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__RelativeMove(soap, &soap_tmp___ptzws__RelativeMove, "-ptzws:RelativeMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__RelativeMoveResponse)
		return soap_closesock(soap);
	ptzws__RelativeMoveResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__RelativeMoveResponse.soap_get(soap, "ptzws:RelativeMoveResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::SendAuxiliaryCommand(const char *endpoint, const char *soap_action, _ptzws__SendAuxiliaryCommand *ptzws__SendAuxiliaryCommand, _ptzws__SendAuxiliaryCommandResponse &ptzws__SendAuxiliaryCommandResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__SendAuxiliaryCommand soap_tmp___ptzws__SendAuxiliaryCommand;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__SendAuxiliaryCommand.ptzws__SendAuxiliaryCommand = ptzws__SendAuxiliaryCommand;
	soap_serializeheader(soap);
	soap_serialize___ptzws__SendAuxiliaryCommand(soap, &soap_tmp___ptzws__SendAuxiliaryCommand);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__SendAuxiliaryCommand(soap, &soap_tmp___ptzws__SendAuxiliaryCommand, "-ptzws:SendAuxiliaryCommand", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__SendAuxiliaryCommand(soap, &soap_tmp___ptzws__SendAuxiliaryCommand, "-ptzws:SendAuxiliaryCommand", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__SendAuxiliaryCommandResponse)
		return soap_closesock(soap);
	ptzws__SendAuxiliaryCommandResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__SendAuxiliaryCommandResponse.soap_get(soap, "ptzws:SendAuxiliaryCommandResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::AbsoluteMove(const char *endpoint, const char *soap_action, _ptzws__AbsoluteMove *ptzws__AbsoluteMove, _ptzws__AbsoluteMoveResponse &ptzws__AbsoluteMoveResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__AbsoluteMove soap_tmp___ptzws__AbsoluteMove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__AbsoluteMove.ptzws__AbsoluteMove = ptzws__AbsoluteMove;
	soap_serializeheader(soap);
	soap_serialize___ptzws__AbsoluteMove(soap, &soap_tmp___ptzws__AbsoluteMove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__AbsoluteMove(soap, &soap_tmp___ptzws__AbsoluteMove, "-ptzws:AbsoluteMove", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__AbsoluteMove(soap, &soap_tmp___ptzws__AbsoluteMove, "-ptzws:AbsoluteMove", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__AbsoluteMoveResponse)
		return soap_closesock(soap);
	ptzws__AbsoluteMoveResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__AbsoluteMoveResponse.soap_get(soap, "ptzws:AbsoluteMoveResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::Stop(const char *endpoint, const char *soap_action, _ptzws__Stop *ptzws__Stop, _ptzws__StopResponse &ptzws__StopResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__Stop soap_tmp___ptzws__Stop;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/Stop";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__Stop.ptzws__Stop = ptzws__Stop;
	soap_serializeheader(soap);
	soap_serialize___ptzws__Stop(soap, &soap_tmp___ptzws__Stop);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__Stop(soap, &soap_tmp___ptzws__Stop, "-ptzws:Stop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__Stop(soap, &soap_tmp___ptzws__Stop, "-ptzws:Stop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__StopResponse)
		return soap_closesock(soap);
	ptzws__StopResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__StopResponse.soap_get(soap, "ptzws:StopResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTours(const char *endpoint, const char *soap_action, _ptzws__GetPresetTours *ptzws__GetPresetTours, _ptzws__GetPresetToursResponse &ptzws__GetPresetToursResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetPresetTours soap_tmp___ptzws__GetPresetTours;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetPresetTours.ptzws__GetPresetTours = ptzws__GetPresetTours;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetPresetTours(soap, &soap_tmp___ptzws__GetPresetTours);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetPresetTours(soap, &soap_tmp___ptzws__GetPresetTours, "-ptzws:GetPresetTours", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetPresetTours(soap, &soap_tmp___ptzws__GetPresetTours, "-ptzws:GetPresetTours", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetPresetToursResponse)
		return soap_closesock(soap);
	ptzws__GetPresetToursResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetPresetToursResponse.soap_get(soap, "ptzws:GetPresetToursResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTour(const char *endpoint, const char *soap_action, _ptzws__GetPresetTour *ptzws__GetPresetTour, _ptzws__GetPresetTourResponse &ptzws__GetPresetTourResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetPresetTour soap_tmp___ptzws__GetPresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetPresetTour.ptzws__GetPresetTour = ptzws__GetPresetTour;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetPresetTour(soap, &soap_tmp___ptzws__GetPresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetPresetTour(soap, &soap_tmp___ptzws__GetPresetTour, "-ptzws:GetPresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetPresetTour(soap, &soap_tmp___ptzws__GetPresetTour, "-ptzws:GetPresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetPresetTourResponse)
		return soap_closesock(soap);
	ptzws__GetPresetTourResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetPresetTourResponse.soap_get(soap, "ptzws:GetPresetTourResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetPresetTourOptions(const char *endpoint, const char *soap_action, _ptzws__GetPresetTourOptions *ptzws__GetPresetTourOptions, _ptzws__GetPresetTourOptionsResponse &ptzws__GetPresetTourOptionsResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetPresetTourOptions soap_tmp___ptzws__GetPresetTourOptions;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetPresetTourOptions.ptzws__GetPresetTourOptions = ptzws__GetPresetTourOptions;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetPresetTourOptions(soap, &soap_tmp___ptzws__GetPresetTourOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetPresetTourOptions(soap, &soap_tmp___ptzws__GetPresetTourOptions, "-ptzws:GetPresetTourOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetPresetTourOptions(soap, &soap_tmp___ptzws__GetPresetTourOptions, "-ptzws:GetPresetTourOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetPresetTourOptionsResponse)
		return soap_closesock(soap);
	ptzws__GetPresetTourOptionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetPresetTourOptionsResponse.soap_get(soap, "ptzws:GetPresetTourOptionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::CreatePresetTour(const char *endpoint, const char *soap_action, _ptzws__CreatePresetTour *ptzws__CreatePresetTour, _ptzws__CreatePresetTourResponse &ptzws__CreatePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__CreatePresetTour soap_tmp___ptzws__CreatePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__CreatePresetTour.ptzws__CreatePresetTour = ptzws__CreatePresetTour;
	soap_serializeheader(soap);
	soap_serialize___ptzws__CreatePresetTour(soap, &soap_tmp___ptzws__CreatePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__CreatePresetTour(soap, &soap_tmp___ptzws__CreatePresetTour, "-ptzws:CreatePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__CreatePresetTour(soap, &soap_tmp___ptzws__CreatePresetTour, "-ptzws:CreatePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__CreatePresetTourResponse)
		return soap_closesock(soap);
	ptzws__CreatePresetTourResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__CreatePresetTourResponse.soap_get(soap, "ptzws:CreatePresetTourResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::ModifyPresetTour(const char *endpoint, const char *soap_action, _ptzws__ModifyPresetTour *ptzws__ModifyPresetTour, _ptzws__ModifyPresetTourResponse &ptzws__ModifyPresetTourResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__ModifyPresetTour soap_tmp___ptzws__ModifyPresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__ModifyPresetTour.ptzws__ModifyPresetTour = ptzws__ModifyPresetTour;
	soap_serializeheader(soap);
	soap_serialize___ptzws__ModifyPresetTour(soap, &soap_tmp___ptzws__ModifyPresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__ModifyPresetTour(soap, &soap_tmp___ptzws__ModifyPresetTour, "-ptzws:ModifyPresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__ModifyPresetTour(soap, &soap_tmp___ptzws__ModifyPresetTour, "-ptzws:ModifyPresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__ModifyPresetTourResponse)
		return soap_closesock(soap);
	ptzws__ModifyPresetTourResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__ModifyPresetTourResponse.soap_get(soap, "ptzws:ModifyPresetTourResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::OperatePresetTour(const char *endpoint, const char *soap_action, _ptzws__OperatePresetTour *ptzws__OperatePresetTour, _ptzws__OperatePresetTourResponse &ptzws__OperatePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__OperatePresetTour soap_tmp___ptzws__OperatePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__OperatePresetTour.ptzws__OperatePresetTour = ptzws__OperatePresetTour;
	soap_serializeheader(soap);
	soap_serialize___ptzws__OperatePresetTour(soap, &soap_tmp___ptzws__OperatePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__OperatePresetTour(soap, &soap_tmp___ptzws__OperatePresetTour, "-ptzws:OperatePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__OperatePresetTour(soap, &soap_tmp___ptzws__OperatePresetTour, "-ptzws:OperatePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__OperatePresetTourResponse)
		return soap_closesock(soap);
	ptzws__OperatePresetTourResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__OperatePresetTourResponse.soap_get(soap, "ptzws:OperatePresetTourResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::RemovePresetTour(const char *endpoint, const char *soap_action, _ptzws__RemovePresetTour *ptzws__RemovePresetTour, _ptzws__RemovePresetTourResponse &ptzws__RemovePresetTourResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__RemovePresetTour soap_tmp___ptzws__RemovePresetTour;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__RemovePresetTour.ptzws__RemovePresetTour = ptzws__RemovePresetTour;
	soap_serializeheader(soap);
	soap_serialize___ptzws__RemovePresetTour(soap, &soap_tmp___ptzws__RemovePresetTour);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__RemovePresetTour(soap, &soap_tmp___ptzws__RemovePresetTour, "-ptzws:RemovePresetTour", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__RemovePresetTour(soap, &soap_tmp___ptzws__RemovePresetTour, "-ptzws:RemovePresetTour", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__RemovePresetTourResponse)
		return soap_closesock(soap);
	ptzws__RemovePresetTourResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__RemovePresetTourResponse.soap_get(soap, "ptzws:RemovePresetTourResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PTZBindingProxy::GetCompatibleConfigurations(const char *endpoint, const char *soap_action, _ptzws__GetCompatibleConfigurations *ptzws__GetCompatibleConfigurations, _ptzws__GetCompatibleConfigurationsResponse &ptzws__GetCompatibleConfigurationsResponse)
{	struct soap *soap = this->soap;
	struct __ptzws__GetCompatibleConfigurations soap_tmp___ptzws__GetCompatibleConfigurations;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver20/ptz/wsdl/GetCompatibleConfigurations";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ptzws__GetCompatibleConfigurations.ptzws__GetCompatibleConfigurations = ptzws__GetCompatibleConfigurations;
	soap_serializeheader(soap);
	soap_serialize___ptzws__GetCompatibleConfigurations(soap, &soap_tmp___ptzws__GetCompatibleConfigurations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ptzws__GetCompatibleConfigurations(soap, &soap_tmp___ptzws__GetCompatibleConfigurations, "-ptzws:GetCompatibleConfigurations", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ptzws__GetCompatibleConfigurations(soap, &soap_tmp___ptzws__GetCompatibleConfigurations, "-ptzws:GetCompatibleConfigurations", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ptzws__GetCompatibleConfigurationsResponse)
		return soap_closesock(soap);
	ptzws__GetCompatibleConfigurationsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ptzws__GetCompatibleConfigurationsResponse.soap_get(soap, "ptzws:GetCompatibleConfigurationsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
